// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdMe9hZWhfbxJVt3bEXKeFnG6scFAFlU',
    appId: '1:499408192380:web:8a125002dfe6bb83845af9',
    messagingSenderId: '499408192380',
    projectId: 'mobile-dev-e5b60',
    authDomain: 'mobile-dev-e5b60.firebaseapp.com',
    storageBucket: 'mobile-dev-e5b60.appspot.com',
    measurementId: 'G-WGBY98EK7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYDZO001bagOy_JzOsGLS4T_gfZvhJIM',
    appId: '1:499408192380:android:07a3b9980987e86c845af9',
    messagingSenderId: '499408192380',
    projectId: 'mobile-dev-e5b60',
    storageBucket: 'mobile-dev-e5b60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD94n6P-9Jwl7-0TeZa2iUXSXw1n9pUEs4',
    appId: '1:499408192380:ios:b28c6eb5d5b71cfb845af9',
    messagingSenderId: '499408192380',
    projectId: 'mobile-dev-e5b60',
    storageBucket: 'mobile-dev-e5b60.appspot.com',
    iosBundleId: 'com.example.pokemonApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD94n6P-9Jwl7-0TeZa2iUXSXw1n9pUEs4',
    appId: '1:499408192380:ios:ca22d765c7b451a3845af9',
    messagingSenderId: '499408192380',
    projectId: 'mobile-dev-e5b60',
    storageBucket: 'mobile-dev-e5b60.appspot.com',
    iosBundleId: 'com.example.pokemonApi.RunnerTests',
  );
}
